name: Playwright Tests (Chromium Only)

on:
  push:
    branches: [ '**' ]
    paths:
      - 'tests/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    name: Run Smoke Tests (Chromium)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright
      run: |
        # Install only Chromium browser
        npx playwright install chromium --with-deps
        # Verify installation
        npx playwright --version
    
    - name: Run Smoke Tests
      run: |
        # Run tests with optimized settings
        PLAYWRIGHT_BROWSERS_PATH=~/.cache/ms-playwright npx playwright test tests/smokeTest.spec.ts \
          --retries=1 \
          --timeout=300000 \
          --project=chromium \
          --workers=2 \
          --reporter=list,html
      env:
        CI: true
        PWDEBUG: 0
        # Add environment variables for faster execution
        PLAYWRIGHT_SKIP_BROWSER_GC: 1
        PLAYWRIGHT_DISABLE_LOGGING: 1
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 7

    - name: Upload blob report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report
        path: blob-report/
        retention-days: 7 