name: Playwright Tests (Chromium Only)

on:
  push:
    branches: [ main ]
    paths:
      - 'tests/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/**'
      - '.github/workflows/playwright.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    name: Run Smoke Tests (Chromium)
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright (Chromium only)
      run: |
        npx playwright install chromium
        npx playwright install-deps chromium
    
    - name: Run Smoke Tests
      run: |
        # Ensure we only run on Chromium
        npx playwright test tests/smokeTest.spec.ts \
          --retries=2 \
          --timeout=300000 \
          --project=chromium \
          --workers=1 \
          --browser=chromium
      env:
        CI: true
        PWDEBUG: 0
        PLAYWRIGHT_BROWSERS_PATH: 0
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Upload blob report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: blob-report
        path: blob-report/
        retention-days: 30 